version: '3'


services: 
  db:
   image: postgres:14
   container_name: shopContaint
   restart: always
   ports:
    - "5432:5432"
   environment:
     POSTGRES_PASSWORD: ${DB_PASSWORD}
     POSTGRES_DB: ${DB_NAME}
   volumes:
    - ./data:/var/lib/postgresql/data   
