version: '3.3'


services: 
  db:
   image: postgres:14
   container_name: shopContaint
   restart: always
   ports:
    - "5432:5432"
   environment:
     POSTGRES_PASSWORD: ${DB_PASSWORD}
     POSTGRES_DB: ${DB_NAME}
   volumes:
    - ./data:/var/lib/postgresql/data   

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin4Containt
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: kalet.svdev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin_123